import type { Metadata } from "next";
import { Bitcount, Bitcount_Single, Doto } from 'next/font/google';
import "./globals.css";

const _fontTitle = Bitcount({
  subsets: ['latin'],
});

const _fontPage = Bitcount_Single({
  subsets: ['latin'],
});

const _fontPre = Doto({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <div className="monitor">
          <div className="monitor-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
